name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "validate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. 
#Make code reviews, branch management, and issue triaging work the way you want.

